export interface PAYMENTS {
  totalRecords: Number,
  data: Data[],
  searchId: null
}

export interface Data {
  transaction_date: string,
  receipt_date: string,
  amount: string,
  charity_amount: string,
  total_amount: string,
  user_structure1: string,
  user_structure2: string,
  user_structure3: string,
  trx_types: string,
  trx_mode: string,
  card_schemes: string,
  payment_id: string,
  order_ref: string,
  authorization: string,
  trx_channel: string,
  accept_method: string,
  acquirer_id: string,
  auth_number: string,
  cet: string,
  cvm: string,
  pan: string,
  mid: number | string,
  mileage: string,
  original_payment_id: string,
  reciept_number: string,
  response_code: string,
  settlement: string,
  settlement_date: string,
  settlement_number: string,
  tpv: string | number,
  user_data1: string,
  user_data2: string,
  user_data3: string,
  user_data4: string,
  user_data5: string,
  vrn_number: string,
  pspid: string,
  application: string,
  tracenum: string,
  forcing_type: string,
  service_type: string,
  p2pe: string,
  card_type: string,
  card_category: string,
  issuer_bank: string,
  issuer_country: string,
  aid: string,
  acquirer_tid: string,
  cashback_amount: string,
  trx_comment: string,
  processing_status: string,
  code_iin: number | string,
  scheme_identifier: string,
  scheme_reference_data: string,
  acquirer_ref_data: string,
  acquirer: string,
  blitz_mode: string,
  host_response_code: string,
  blitz_decision_code: string,
  rejection_reason: string,
  fnci_answer: string,
  session_number: string,
  guarantor_answer: string,
  cheque_no: string,
  account_no: string,
  visu_fnci: string,
  degraded_mode_indicator: string,
  allowed_forcing_code: string,
  currency: string,
  tips_amount: string,
  refundable: boolean,
  isSaleAvailable: boolean,
  isReceiptAvailable: boolean,
  processingDate: string,
  _id?: string,
  order_id?: string
}

